[package]
name = "libcsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "alloc", "zmq"]
std = ["libcsp-sys/std", "dep:once_cell"]
alloc = ["libcsp-sys/alloc"]

zmq = ["std", "libcsp-sys/zmq"]
usart = ["std", "libcsp-sys/usart"]
socketcan = ["std", "libcsp-sys/socketcan"]

[dependencies]
libcsp-sys = { path = "../libcsp-sys", default-features = false }
once_cell = { version = "1.19.0", optional = true }
spin = { version = "0.9.8", features = ["mutex", "lock_api", "lazy"] }
